name: build
on: [ push, pull_request ]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ clang, gcc, gcc-9, gcc-10, gcc-11, gcc-12 ]
    steps:
      - name: Add repository
        run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
      - name: Install packages
        run: sudo apt install gettext gcc-9 gcc-10 gcc-11 gcc-12
      - uses: actions/checkout@v2
      - name: Autoconf
        run: autoreconf -i -f
      - name: Configure
        run: ./configure
        env:
          CC: ${{ matrix.compiler }}
      - name: Make
        run: make
      - name: Run tests
        run: make check
      - name: Generate corpus
        run: make generate_corpus
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [ clang, gcc ]
    steps:
      - name: Install packages
        run: brew install automake
      - uses: actions/checkout@v2
      - name: Autoconf
        run: autoreconf -i -f
      - name: Configure
        run: ./configure
        env:
          CC: ${{ matrix.compiler }}
      - name: Make
        run: make
      - name: Run tests
        run: make check
      - name: Generate corpus
        run: make generate_corpus
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            autotools
            base-devel
            gcc
            libiconv-devel
      - uses: actions/checkout@v2
      - name: Autoconf
        run: autoreconf -i -f
      - name: Configure
        run: ./configure
      - name: Make
        run: make
      - name: Test
        run: make check
      - name: Log
        run: cat ./test-suite.log
